import mongoose from 'mongoose';

// --- Main Organization Schema ---

const OrganizationSchema = new mongoose.Schema({
    name: { type: String, required: true },
    plan: {
        type: String,
        default: 'free'
    },
    industry: { type: String, default: 'generic', maxlength: 60 }, // 'clinic', 'ecommerce', 'generic'
    subCategory: { type: String, maxlength: 60 },
    industry_version: { type: String, default: "0.0.0" }, // For "Update Available" logic
    industry_settings: {
        persona: { type: String, default: 'professional' }, // 'friendly', 'empathetic'
    },

    // 🧬 NEW FIELDS (Business DNA)
    accountType: { type: String, enum: ['business', 'individual', 'student'], default: 'business' },
    logo: { type: String },
    bannerImage: { type: String },
    tagline: { type: String, maxlength: 140 },
    businessDescription: { type: String, maxlength: 1200 },
    businessModel: { type: String, maxlength: 60 },
    targetAudience: { type: String, maxlength: 60 },
    primaryGoal: { type: String, maxlength: 60 },
    heroOffering: { type: String, maxlength: 800 },
    communicationTone: { type: String, default: 'professional' }, // mapped from industry_settings persona conceptually
    aiConstitution: { type: String }, // Global guidelines for all AI agents
    aiRestrictions: { type: String }, // Strict limits/don'ts for all AI agents

    companySize: { type: String }, // e.g., '1-10', '11-50', '51-200'
    foundedYear: { type: String }, // e.g., '2015'
    policies: {
        privacyPolicy: { type: String }, // URL
        termsOfService: { type: String }, // URL
        refundPolicy: { type: String } // URL
    },

    // Contact
    contactPhone: { type: String },
    contactEmail: { type: String },
    website: { type: String },
    contactChannels: [{
        id: String,
        type: String, // email, phone, website, address, location
        value: String,
        enabled: { type: Boolean, default: true }
    }],
    socialLinks: [{
        id: String,
        platform: String, // linkedin, twitter, instagram, etc.
        url: String,
        enabled: { type: Boolean, default: true }
    }],
    operatingHours: {
        enabled: { type: Boolean, default: true },
        type: {
            type: String,
            enum: ['24/7', 'business_hours', 'custom']
        },
        weeklyHours: { type: mongoose.Schema.Types.Mixed }
    },
    businessAddress: {
        street: { type: String },
        city: { type: String },
        state: { type: String },
        country: { type: String },
        pincode: { type: String },
    },

    // Metadata
    onboardingCompleted: { type: Boolean, default: false },
    onboardingStep: { type: Number, default: 0 },

    // 🧠 AI Knowledge Strategy Guide (Generated by Gemini)
    knowledge_strategy: { type: mongoose.Schema.Types.Mixed },

    installed_templates: [String], // Track all installed template slugs
    planStartDate: { type: Date, default: Date.now },
    planEndDate: { type: Date }, // For subscription management

    // 🔒 SUBSCRIPTION SNAPSHOT (Locked Plan Configuration)
    subscription: {
        plan_id: { type: String }, // Reference to global plan (for admin tracking)
        token_capacity: { type: Number }, // 🟢 Explicitly store purchased capacity

        // 🟢 Detailed Token Breakdown (Requested by User)
        tokens_plan: { type: Number, default: 0 },
        tokens_rollover: { type: Number, default: 0 },
        tokens_topup: { type: Number, default: 0 },

        subscribed_at: { type: Date }, // Purchase timestamp
        expires_at: { type: Date }, // Expiration date
        status: {
            type: String,
            enum: ['active', 'expired', 'cancelled', 'trial', 'paused'],
            default: 'trial'
        },

        // Complete plan snapshot - locked at purchase time
        snapshot: {
            plan_name: { type: String },
            price_paid: { type: Number }, // Keep for legacy compatibility
            price_offer: { type: Number }, // 🟢 Added: Final Price Paid
            price_market: { type: Number }, // 🟢 Added: Market List Price
            currency: { type: String, default: 'INR' },
            billing_cycle: { type: String }, // 'monthly' | 'yearly'
            timestamp: { type: String }, // 🟢 Added

            // Features with locked multipliers
            features: [{
                id: String,
                name: String,
                icon: String,
                color: String,
                status: String,
                category: String,
                description: String,
                enabled: Boolean,  // 🟢 Added
                value: mongoose.Schema.Types.Mixed, // 🟢 Added (can be number or string)

                // Sub-features (cost components) with LOCKED rates
                includes: [{
                    id: String,    // 🟢 Added
                    name: String,
                    value: mongoose.Schema.Types.Mixed, // 🟢 Added
                    unit: String,
                    baseMultiplier: Number,
                    sellMultiplier: Number,  // 🔒 FROZEN at purchase time
                    description: String,
                    costReason: String
                }]
            }],

            // Quota limits (LOCKED)
            limits: {
                max_tokens: { type: Number },
                max_chats: { type: Number },
                max_file_uploads: { type: Number },
                max_website_pages: { type: Number },
                max_kb_size_mb: { type: Number },
                brain_capacity_mb: { type: Number }, // 🟢 Added (Alias)
                max_bots: { type: Number },
                max_team_members: { type: Number },
                max_websites: { type: Number }, // 🟢 Added
                data_retention_days: { type: Number }, // 🟢 Added
                max_manual_qa: { type: Number }, // 🟢 Added
                max_forms: { type: Number }, // 🟢 Added
                rollover_percentage: { type: Number }, // 🟢 Added
                rollover_validity_days: { type: Number }, // 🟢 Added (Harmonized)
                max_team_seats: { type: Number } // 🟢 Added (Alias for max_team_members)
            },

            // ✅ Store Complete Order Summary (Discounts, Coupons, etc.)
            order_summary: {
                subtotal: Number,
                duration_months: Number,
                duration_discount: Number,
                coupon_code: String,
                coupon_discount: Number,
                total_savings: Number,
                final_total: Number
            }
        }
    },

    usage: {
        tokensUsed: { type: Number, default: 0 },
        words_used: { type: Number, default: 0 },
        words_limit: { type: Number, default: 200000 }, // Monthly Plan Limit
        topup_balance: { type: Number, default: 0 }, // 🟢 Extra Purchased Tokens (No Expiry/Different Validity)
        topup_limit: { type: Number, default: 0 },   // 🟢 Total Purchased Top-up Tokens (For "Used/Total" Tracking)
        chatbotsCreated: { type: Number, default: 0 },
        websitePagesAdded: { type: Number, default: 0 },
        filesUploaded: { type: Number, default: 0 },
        leadFormsCreated: { type: Number, default: 0 },
        automationFlowsCreated: { type: Number, default: 0 },
        rollover_tokens: { type: Number, default: 0 }, // 🟢 Renamed
        rollover_expires_at: { type: Date }, // 🟢 Added
        last_rollover_count: { type: Number, default: 0 }, // 🟢 Added (For visibility)
        lastResetDate: { type: Date, default: Date.now }, // For monthly limits reset

        // 🧠 Storage Breakdown (MB tracking for Neural Brain)
        storage_breakdown: {
            documents_mb: { type: Number, default: 0 },
            websites_mb: { type: Number, default: 0 },
            training_mb: { type: Number, default: 0 },
            chat_history_mb: { type: Number, default: 0 },
            forms_mb: { type: Number, default: 0 },
            auto_learning_mb: { type: Number, default: 0 },
            total_mb: { type: Number, default: 0 }
        },
        storage_by_system: {
            minio_mb: { type: Number, default: 0 },       // File storage (PDFs, images)
            mongodb_mb: { type: Number, default: 0 },     // Database documents & metadata
            chroma_mb: { type: Number, default: 0 },      // Vector embeddings
            total_mb: { type: Number, default: 0 }         // Sum of all three
        }
    },
    lead_schemas: [{
        key: { type: String, required: true },
        question: { type: String, required: true },
        type: {
            type: String,
            enum: ['text', 'number', 'email', 'phone', 'date', 'dropdown'],
            default: 'text'
        },
        options: [String], // For dropdowns
        required: { type: Boolean, default: false },
        section: { type: String, default: 'General' },
        trigger: {
            type: String,
            enum: ['immediate', 'smart', 'checkout'],
            default: 'smart'
        }
    }],
    created_at: { type: Date, default: Date.now },
    users_access: [{
        userId: { type: String, required: true },
        name: String,
        email: String,
        password_hash: String,
        googleId: String,
        image: { type: String }, // Google profile picture URL
        secondaryEmail: {
            email: String,
            password_hash: String,
            linkedAt: { type: Date, default: Date.now }
        },
        resetPasswordToken: String,
        resetPasswordExpires: Date,
        role: { type: String, enum: ['owner', 'admin', 'manager', 'employee', 'viewer'], default: 'viewer' },
        permissions: [String],
        isActive: { type: Boolean, default: true },
        activationToken: String,
        activationExpires: Date,
        invitedAt: Date,
        invitedBy: String
    }],
    brainId: { type: mongoose.Schema.Types.ObjectId, ref: 'Brain' },
    is_deleted: { type: Boolean, default: false },
    available_ribbons: {
        type: [String],
        default: []
    }, // Global "Ribbon Pool" (Max 30)
    deletedAt: { type: Date },

    // 🔒 Security & Billing Logs
    hasUsedFreePlan: { type: Boolean, default: false }, // 🟢 Added (Phase 23)

    // 🧾 KYC & Billing Address (Safe Payment Gate)
    billing_info: {
        company_name: String,
        address_line1: String,
        address_line2: String,
        city: String,
        state: String,
        state_name: String, // Full state name (e.g. "Uttar Pradesh")
        pincode: String,
        country: String,
        country_name: String, // Full country name (e.g. "India")
        phone: String,
        tax_id: String // GSTIN or Tax ID
    },

    // --- 🏛️ Data Governance (Enterprise Control Center) ---
    governance: {
        // 1. Retention Policy (Cost Control)
        retention_policy_days: {
            type: Number,
            default: -1, // -1 = Forever, 30 = 30 Days, 365 = 1 Year
            min: -1
        },

        // 2. User Privileges (Compliance Control)
        allow_user_delete: {
            type: Boolean,
            default: false // Banks/Support default to OFF (Users can't hide evidence)
        },

        // 3. Admin Safety (Prevent Accidents)
        require_export_before_delete: {
            type: Boolean,
            default: true // Pop-up "Download PDF" before delete
        }
    }
}, {
    timestamps: true,
    toJSON: { virtuals: true },
    toObject: { virtuals: true }
});

// Virtual for billing logs
OrganizationSchema.virtual('billingLogs', {
    ref: 'Transaction', // Updated to use Transaction model
    localField: '_id',
    foreignField: 'organizationId'
});

// 🟢 Virtual for Activity Logs (BMW Dashboard)
OrganizationSchema.virtual('activityLogs', {
    ref: 'ActivityLog',
    localField: '_id',
    foreignField: 'organizationId'
});

// 🟢 Virtual for Total Tokens (Plan + Rollover + Topup)
OrganizationSchema.virtual('usage.total_tokens').get(function () {
    const limit = this.usage?.words_limit || 0;
    const rollover = this.usage?.rollover_tokens || 0;
    const topup = this.usage?.topup_balance || 0;
    return limit + rollover + topup;
});

export const Organization = mongoose.model('Organization', OrganizationSchema);
