import mongoose, { Schema, Document } from 'mongoose';

export interface IApiSource extends Document {
    orgId: string;
    name: string;
    endpoint: string;
    method: 'GET' | 'POST';

    // Authentication
    authType: 'none' | 'api-key' | 'bearer' | 'basic';
    authCredentials: {
        apiKey?: string;
        token?: string;
        username?: string;
        password?: string;
        headerName?: string;
        headers?: Map<string, string>;
    };

    // Request Configuration
    requestConfig: {
        searchParam: string;
        paginationParams?: {
            pageParam: string;
            limitParam: string;
            defaultLimit: number;
        };
        bodyTemplate?: string; // For POST APIs
    };

    // Field Mapping
    fieldMapping: Map<string, {
        displayName: string;
        type: 'text' | 'number' | 'date' | 'boolean';
        searchable: boolean;
    }>;

    // Metadata
    tags?: string[]; // Added Tags Support
    summary?: string;
    intent_summary?: string;
    category?: string; // e.g., 'sales', 'support'

    // Behavior
    syncMode: 'real-time' | 'scheduled' | 'one-time';
    refreshSchedule?: 'hourly' | 'daily' | 'weekly';
    cacheConfig?: {
        enabled: boolean;
        ttlMinutes: number;
    };

    isActive: boolean;
    page_index?: string;
    page_index_meta?: any;
    lastSynced?: Date;
    createdAt: Date;
    updatedAt: Date;
}

const ApiSourceSchema = new Schema<IApiSource>({
    orgId: {
        type: String,
        required: true,
        ref: 'Organization',
        index: true
    },
    name: {
        type: String,
        required: true,
        trim: true
    },
    endpoint: {
        type: String,
        required: true,
        trim: true
    },
    method: {
        type: String,
        enum: ['GET', 'POST'],
        default: 'GET'
    },
    authType: {
        type: String,
        enum: ['none', 'api-key', 'bearer', 'basic'],
        default: 'none'
    },
    authCredentials: {
        apiKey: { type: String, select: false }, // Sensitive data
        token: { type: String, select: false },
        username: { type: String, select: false },
        password: { type: String, select: false },
        headerName: { type: String },
        headers: { type: Map, of: String } // Dynamic headers support
    },
    requestConfig: {
        searchParam: {
            type: String,
            required: true,
            default: 'q'
        },
        paginationParams: {
            pageParam: String,
            limitParam: String,
            defaultLimit: {
                type: Number,
                default: 50,
                min: 1,
                max: 500
            }
        },
        bodyTemplate: String
    },
    fieldMapping: {
        type: Map,
        of: new Schema({
            displayName: { type: String, required: true },
            type: {
                type: String,
                enum: ['text', 'number', 'date', 'boolean'],
                default: 'text'
            },
            searchable: { type: Boolean, default: true }
        }, { _id: false })
    },
    syncMode: {
        type: String,
        enum: ['real-time', 'scheduled', 'one-time'],
        default: 'real-time'
    },
    refreshSchedule: {
        type: String,
        enum: ['hourly', 'daily', 'weekly']
    },
    cacheConfig: {
        enabled: { type: Boolean, default: true },
        ttlMinutes: { type: Number, default: 5, min: 1, max: 1440 }
    },
    isActive: {
        type: Boolean,
        default: true
    },
    tags: {
        type: [String],
        index: true
    },
    summary: String,
    intent_summary: String,
    category: {
        type: String,
        default: 'other'
    },
    page_index: { type: String }, // 🔥 YAML Tree Structure generated by Neural Indexer
    page_index_meta: { type: Object }, // Metadata about the index (tokens, confidence, etc)
    lastSynced: Date
}, {
    timestamps: true
});

// Indexes for performance
ApiSourceSchema.index({ orgId: 1, isActive: 1 });
ApiSourceSchema.index({ orgId: 1, syncMode: 1 });

// Encrypt sensitive fields before saving
ApiSourceSchema.pre('save', async function (next) {
    if (this.isModified('authCredentials')) {
        // TODO: Add encryption using crypto module
        // For now, marking as sensitive data (select: false prevents accidental exposure)
    }
    next();
});

export const ApiSource = mongoose.model<IApiSource>('ApiSource', ApiSourceSchema);
