import mongoose from 'mongoose';

const KnowledgeDocumentSchema = new mongoose.Schema({
    orgId: { type: mongoose.Schema.Types.ObjectId, ref: 'Organization', required: true, index: true },
    brainId: { type: mongoose.Schema.Types.ObjectId, ref: 'Brain', index: true }, // NEW: Linked to Brain Collection
    name: { type: String, required: true },
    url: { type: String, required: true }, // S3/Storage URL
    file_type: { type: String, required: true }, // pdf, docx, txt
    size: Number,
    token_count: Number,
    chunk_count: Number,
    chunk_ids: [{ type: String }],
    chunk_hashes: [{ type: String }], // 🔥 Added for Smart Diffing
    page_index: { type: String }, // 🔥 YAML Tree Structure generated by Neural Indexer
    page_index_meta: { type: Object }, // Metadata about the index (tokens, confidence, etc)
    isActive: { type: Boolean, default: true },
    tags: [{ type: String }],
    summary: String,      // AI Summary
    intent_summary: String, // What questions can this answer?
    status: { type: String, enum: ['draft', 'processing', 'ready', 'failed'], default: 'processing' },
    uploadedAt: { type: Date, default: Date.now },
    metadata: { type: Object }
});

export const KnowledgeDocument = mongoose.model('KnowledgeDocument', KnowledgeDocumentSchema);