import mongoose from 'mongoose';

const ManualDocumentSchema = new mongoose.Schema({
    orgId: { type: mongoose.Schema.Types.ObjectId, ref: 'Organization', required: true, index: true },
    title: { type: String, required: true },
    description: String,
    content: { type: String, required: true }, // Save HTML/Text
    isActive: { type: Boolean, default: true },
    status: { type: String, enum: ['draft', 'pending', 'training', 'active', 'failed'], default: 'active' },
    tags: [String],
    intent_summary: String, // What questions can this entry answer?
    priority: { type: String, enum: ['high', 'normal', 'low'], default: 'high' },
    token_count: Number,
    chunk_count: Number,
    chunk_ids: [{ type: String }], // 🔥 Added for referencing vectors
    chunk_hashes: [{ type: String }], // 🔥 Added for Smart Diffing
    page_index: { type: String }, // 🔥 YAML Tree Structure generated by Neural Indexer
    page_index_meta: { type: Object }, // Metadata about the index (tokens, confidence, etc)
    last_updated: Date,
    createdAt: { type: Date, default: Date.now }
}, { timestamps: true });

export const ManualDocument = mongoose.model('ManualDocument', ManualDocumentSchema);
