import mongoose from 'mongoose';

// 🌐 UI Element Schema — Captured during DOM scan at crawl time
const UiElementSchema = new mongoose.Schema({
    element_type: { type: String, enum: ['button', 'link', 'input', 'form', 'nav', 'other'], default: 'other' },
    selector: String,       // CSS selector, e.g. '#submit-btn'
    aria_label: String,     // e.g. 'Add to Cart'
    text: String,           // innerText
    href: String,           // For <a> tags
    id: String,             // Raw element ID
    name: String,           // name attribute (for inputs)
}, { _id: false });

const PageSchema = new mongoose.Schema({
    url: { type: String, required: true },
    title: String,
    summary: String,
    intent_summary: String, // What questions can this page answer?
    ai_tags: [String],
    status: { type: String, enum: ['draft', 'trained', 'pending', 'ignored', 'crawling', 'embedding', 'failed'], default: 'pending' },
    error_message: String,
    isActive: { type: Boolean, default: true },
    crawl_frequency: { type: String, default: '14d' },
    last_crawled: Date,
    token_count: Number,
    chunk_count: { type: Number, default: 0 },
    chunk_ids: [String],
    chunk_hashes: [String], // 🔥 Added for Smart Diffing
    page_index: { type: String }, // 🔥 YAML Tree Structure generated by Neural Indexer
    page_index_meta: { type: Object }, // Metadata about the index (tokens, confidence, etc)
    raw_url: String, // 🔥 Deep Research: MinIO Path
    ui_elements: [UiElementSchema] // 🌐 UI Teleporter: DOM Selectors (Skill 13)
});

const SiteSchema = new mongoose.Schema({
    orgId: { type: mongoose.Schema.Types.ObjectId, ref: 'Organization', required: true, index: true }, // Link to Org
    brainId: { type: mongoose.Schema.Types.ObjectId, ref: 'Brain', index: true }, // NEW: Linked to Brain Collection
    domain: { type: String, required: true },
    icon: String,
    description: String,
    intent_summary: String, // What questions can this whole site answer?
    chunk_count: { type: Number, default: 0 },
    token_count: { type: Number, default: 0 },
    tags: [String],
    status: { type: String, enum: ['draft', 'active', 'error', 'crawling', 'embedding', 'failed'], default: 'active' }, // active, error, crawling, draft, embedding, failed
    crawl_schedule: {
        type: String,
        enum: ['weekly', 'bi-weekly', 'monthly', 'never'],
        required: true  // User MUST choose frequency
    },
    pages: [PageSchema], // Pages Array (Watch for 16MB here too inside Site, but better than inside Org)
    allowUI_Actions: { type: Boolean, default: false }, // 🌐 Skill 13 Opt-In: User allows AI-driven DOM navigation
    createdAt: { type: Date, default: Date.now },
    updatedAt: { type: Date, default: Date.now }
});

// Index for fast lookup by Org
SiteSchema.index({ orgId: 1, domain: 1 }, { unique: true });

export const Site = mongoose.model('Site', SiteSchema);
